-- ============================================================
-- BANCO ANDINO - DROP ALL TABLES
-- Ejecutar ANTES de 01_DDL_create_tables.sql
-- Elimina tablas en orden inverso de dependencia (FKs)
-- PostgreSQL 15+ | Base de datos: banco_andino
-- ============================================================

-- ============================================================
-- PASO 0: OPCION NUCLEAR (más rápido para desarrollo)
-- Elimina TODO el schema public y lo recrea limpio
-- USAR SOLO EN AMBIENTE DE DESARROLLO / LOCAL
-- ============================================================

-- DROP SCHEMA public CASCADE;
-- CREATE SCHEMA public;

-- ============================================================
-- PASO 1: DROP TABLAS NUEVAS (banco_andino)
-- En orden inverso: primero las que tienen FKs hacia otras
-- ============================================================

-- Home banking
DROP TABLE IF EXISTS USUARIOS_HOMEBANKING CASCADE;

-- Metas y KPIs
DROP TABLE IF EXISTS FMETATIPOCREDITO CASCADE;
DROP TABLE IF EXISTS FMETAAGENCIA CASCADE;
DROP TABLE IF EXISTS FMETASASESOR CASCADE;
DROP TABLE IF EXISTS DTIPOCREDITO CASCADE;

-- Riesgos
DROP TABLE IF EXISTS FENTIDADESRELACIONADAS CASCADE;
DROP TABLE IF EXISTS DENTIDADFINANCIERA CASCADE;

-- Operaciones / transferencias / pagos
DROP TABLE IF EXISTS FDEBITOAFILIACION CASCADE;
DROP TABLE IF EXISTS FGIRO CASCADE;
DROP TABLE IF EXISTS DGIRO CASCADE;
DROP TABLE IF EXISTS DESTADOGIRO CASCADE;
DROP TABLE IF EXISTS DNOCLIENTEUSUARIO CASCADE;
DROP TABLE IF EXISTS FCONVENIO CASCADE;
DROP TABLE IF EXISTS DDEBITOAUTOMATICO CASCADE;
DROP TABLE IF EXISTS DCANALGIRO CASCADE;
DROP TABLE IF EXISTS DCONVENIO CASCADE;
DROP TABLE IF EXISTS FOPERACIONES CASCADE;
DROP TABLE IF EXISTS DCANALTRANSACCIONAL CASCADE;
DROP TABLE IF EXISTS DMEDIOPAGO CASCADE;
DROP TABLE IF EXISTS DTIPOOPERACION CASCADE;
DROP TABLE IF EXISTS DCONCEPTOOPERACION CASCADE;

-- Ahorros
DROP TABLE IF EXISTS FCUENTAAHORROMULTIPLE CASCADE;
DROP TABLE IF EXISTS FCUENTAAHORROPROGRAMADO CASCADE;
DROP TABLE IF EXISTS FCUENTAAHORRO CASCADE;
DROP TABLE IF EXISTS DCUENTAAHORRO CASCADE;
DROP TABLE IF EXISTS DOPERADOR CASCADE;
DROP TABLE IF EXISTS DAUXILIAR CASCADE;
DROP TABLE IF EXISTS DESTADOCUENTA CASCADE;
DROP TABLE IF EXISTS DTIPOTASAAHORRO CASCADE;
DROP TABLE IF EXISTS DTIPOCUENTAAHORRO CASCADE;
DROP TABLE IF EXISTS DPRODUCTOAHORRO CASCADE;

-- Crédito — hechos y transaccionales
DROP TABLE IF EXISTS FGARANTIAS CASCADE;
DROP TABLE IF EXISTS FPLANPAGOMES CASCADE;
DROP TABLE IF EXISTS FAGCUENTACREDITO CASCADE;
DROP TABLE IF EXISTS DCUENTACREDITO CASCADE;

-- Evaluaciones
DROP TABLE IF EXISTS FEVALMICROACTIVO CASCADE;
DROP TABLE IF EXISTS FEVALEMPRESARIAL CASCADE;
DROP TABLE IF EXISTS FEVALCONSUMO CASCADE;
DROP TABLE IF EXISTS DEVALUACION CASCADE;

-- Solicitud
DROP TABLE IF EXISTS DSOLICITUD CASCADE;
DROP TABLE IF EXISTS DSOLICITUDSITUACION CASCADE;
DROP TABLE IF EXISTS DSOLICITUDESTADO CASCADE;

-- Dimensiones crédito
DROP TABLE IF EXISTS DESTADODESEMBOLSO CASCADE;
DROP TABLE IF EXISTS DMODALIDADPAGO CASCADE;
DROP TABLE IF EXISTS DGARANTIA CASCADE;
DROP TABLE IF EXISTS DADEUDADO CASCADE;
DROP TABLE IF EXISTS DCANALDESEMBOLSO CASCADE;
DROP TABLE IF EXISTS DCOMITE CASCADE;
DROP TABLE IF EXISTS DNIVELAPROBACION CASCADE;
DROP TABLE IF EXISTS DSUBRECURSO CASCADE;
DROP TABLE IF EXISTS DRECURSO CASCADE;
DROP TABLE IF EXISTS DCALIFICACIONCREDITICIA CASCADE;
DROP TABLE IF EXISTS DCONDICIONCONTABLE CASCADE;
DROP TABLE IF EXISTS DESTADOCREDITO CASCADE;
DROP TABLE IF EXISTS DGRUPOCREDITO CASCADE;
DROP TABLE IF EXISTS DTIPOTASA CASCADE;
DROP TABLE IF EXISTS DMODALIDAD CASCADE;
DROP TABLE IF EXISTS DPRODUCTO CASCADE;

-- Cliente
DROP TABLE IF EXISTS FCLIENTEFUENTEINGRESO CASCADE;
DROP TABLE IF EXISTS FCLIENTEUBIGEO CASCADE;
DROP TABLE IF EXISTS DCLIENTE CASCADE;

-- Personal y organización
DROP TABLE IF EXISTS DPERSONAL CASCADE;
DROP TABLE IF EXISTS DCARGOPERSONAL CASCADE;
DROP TABLE IF EXISTS DASESORNIVEL CASCADE;
DROP TABLE IF EXISTS DASESOR CASCADE;
DROP TABLE IF EXISTS DADMINISTRADOR CASCADE;
DROP TABLE IF EXISTS DJEFEREGIONAL CASCADE;
DROP TABLE IF EXISTS DAGENCIA CASCADE;

-- Tiempo
DROP TABLE IF EXISTS DTIEMPO CASCADE;
DROP TABLE IF EXISTS DTIEMPOMES CASCADE;

-- Catálogo base
DROP TABLE IF EXISTS GENT_TIPCAMBIO CASCADE;
DROP TABLE IF EXISTS DMONEDA CASCADE;
DROP TABLE IF EXISTS DACTIVIDADECONOMICA CASCADE;
DROP TABLE IF EXISTS DSECTORECONOMICO CASCADE;
DROP TABLE IF EXISTS DCLASEPERSONA CASCADE;
DROP TABLE IF EXISTS DTIPODOCUMENTOIDENTIDAD CASCADE;
DROP TABLE IF EXISTS DTIPOVIA CASCADE;
DROP TABLE IF EXISTS DPAIS CASCADE;
DROP TABLE IF EXISTS DUBIGEO CASCADE;

-- ============================================================
-- PASO 2: DROP TABLAS ANTIGUAS (script Power BI anterior)
-- Por si quedaron de una ejecución previa
-- ============================================================

DROP TABLE IF EXISTS KPIS_CARTERA_MENSUAL CASCADE;
DROP TABLE IF EXISTS SCORING_MENSUAL CASCADE;
DROP TABLE IF EXISTS KPYDPLANPAGCRE CASCADE;
DROP TABLE IF EXISTS GENMCRECLI CASCADE;
DROP TABLE IF EXISTS KPYMCRECONVEN CASCADE;
DROP TABLE IF EXISTS SIPMPERSONAL CASCADE;
DROP TABLE IF EXISTS CLIMCLIENTES CASCADE;
DROP TABLE IF EXISTS GENTTipCambio CASCADE;
DROP TABLE IF EXISTS SIPTAreaOrg CASCADE;
DROP TABLE IF EXISTS SIPTCARGOPER CASCADE;
DROP TABLE IF EXISTS KPYTConCredit CASCADE;
DROP TABLE IF EXISTS KPYTEstCreCon CASCADE;
DROP TABLE IF EXISTS KPYTSUBTIPCRE CASCADE;
DROP TABLE IF EXISTS GENTOficinas CASCADE;
DROP TABLE IF EXISTS GentZonas CASCADE;

-- ============================================================
-- VERIFICACION (opcional — ejecutar después del DROP)
-- ============================================================
-- SELECT tablename FROM pg_tables
-- WHERE schemaname = 'public'
-- ORDER BY tablename;
-- Resultado esperado: 0 filas
