-- ============================================================
-- BANCO ANDINO - BASE DE DATOS COMPARTIDA (ENTIDAD FICTICIA)
-- Ambiente: Académico / Portal Mi Banco + Core Financiero + Power BI
-- Propósito: Simulación de core bancario para uso educativo
-- Referencia paramétrica: institución financiera peruana (memorias anuales + boletines SBS públicos).
-- KPIs usados únicamente como calibración paramétrica. Datos de acceso público.
-- Entidad simulada: Banco Andino (100% ficticio).
-- PostgreSQL 15+ | Base de datos: banco_andino | Schema: public
-- ============================================================

-- ============================================================
-- BLOQUE 0: EXTENSIONES
-- ============================================================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- BLOQUE 1: DIMENSIONES GEOGRAFICAS Y CATALOGO BASE
-- ============================================================

CREATE TABLE DUBIGEO (
    PKUBIGEO            SERIAL          PRIMARY KEY,
    CODDEPARTAMENTO     CHAR(2)         NOT NULL,
    DESDEPARTAMENTO     VARCHAR(60)     NOT NULL,
    CODPROVINCIA        CHAR(4)         NOT NULL,
    DESPROVINCIA        VARCHAR(60)     NOT NULL,
    CODDISTRITO         CHAR(6)         NOT NULL,
    DESDISTRITO         VARCHAR(60)     NOT NULL,
    CODZONA             CHAR(4)         NULL,
    DESZONA             VARCHAR(60)     NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DPAIS (
    PKPAIS              SERIAL          PRIMARY KEY,
    CODPAIS             CHAR(3)         NOT NULL UNIQUE,
    DESPAIS             VARCHAR(60)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DTIPOVIA (
    PKTIPOVIA           SERIAL          PRIMARY KEY,
    CODTIPOVIA          CHAR(2)         NOT NULL UNIQUE,
    DESTIPOVIA          VARCHAR(40)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DTIPODOCUMENTOIDENTIDAD (
    PKTIPODOCUMENTOIDENTIDAD  SERIAL    PRIMARY KEY,
    CODTIPODOCUMENTOIDENTIDAD CHAR(2)   NOT NULL UNIQUE,
    DESTIPODOCUMENTOIDENTIDAD VARCHAR(40) NOT NULL,
    FECULTACTUALIZACION       TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE DCLASEPERSONA (
    PKCLASEPERSONA      SERIAL          PRIMARY KEY,
    CODCLASEPERSONA     CHAR(2)         NOT NULL UNIQUE,
    DESCLASEPERSONA     VARCHAR(40)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DSECTORECONOMICO (
    PKSECTORECONOMICO   SERIAL          PRIMARY KEY,
    CODSECTORECONOMICO  CHAR(3)         NOT NULL UNIQUE,
    DESSECTORECONOMICO  VARCHAR(60)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DACTIVIDADECONOMICA (
    PKACTIVIDADECONOMICA  SERIAL        PRIMARY KEY,
    CODACTIVIDADECONOMICA CHAR(6)       NOT NULL UNIQUE,
    DESACTIVIDADECONOMICA VARCHAR(100)  NOT NULL,
    PKSECTORECONOMICO     INT           NOT NULL REFERENCES DSECTORECONOMICO(PKSECTORECONOMICO),
    FECULTACTUALIZACION   TIMESTAMP     NOT NULL DEFAULT NOW()
);

CREATE TABLE DMONEDA (
    PKMONEDA            SERIAL          PRIMARY KEY,
    CODMONEDA           CHAR(2)         NOT NULL UNIQUE,
    DESMONEDA           VARCHAR(30)     NOT NULL,
    SIMBOLO             CHAR(3)         NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- Tipo de cambio diario (consumido por core financiero y Power BI)
CREATE TABLE GENT_TIPCAMBIO (
    PKTIPCAMBIO         SERIAL          PRIMARY KEY,
    FECTIPCAMBIO        DATE            NOT NULL UNIQUE,
    NTIPCAMFIJ          NUMERIC(8,4)    NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- ============================================================
-- BLOQUE 2: DIMENSION TIEMPO
-- ============================================================

CREATE TABLE DTIEMPOMES (
    PERIODOMES          INT             PRIMARY KEY,  -- YYYYMM
    MES                 SMALLINT        NOT NULL,
    ANIO                SMALLINT        NOT NULL,
    DESCRIPCIONMES      VARCHAR(20)     NOT NULL,
    BIMESTRE            SMALLINT        NOT NULL,
    TRIMESTRE           SMALLINT        NOT NULL,
    CUATRIMESTRE        SMALLINT        NOT NULL,
    SEMESTRE            SMALLINT        NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DTIEMPO (
    PERIODODIA          INT             PRIMARY KEY,  -- YYYYMMDD
    DIA                 SMALLINT        NOT NULL,
    MES                 SMALLINT        NOT NULL,
    ANIO                SMALLINT        NOT NULL,
    PERIODOMES          INT             NOT NULL REFERENCES DTIEMPOMES(PERIODOMES),
    DESCRIPCIONDIA      VARCHAR(20)     NOT NULL,
    DIASEMANA           SMALLINT        NOT NULL,
    DIAANIO             SMALLINT        NOT NULL,
    SEMANAANIO          SMALLINT        NOT NULL,
    SEMANAMES           SMALLINT        NOT NULL,
    DESCRIPCIONMES      VARCHAR(20)     NOT NULL,
    FERIADO             CHAR(1)         NOT NULL DEFAULT 'N',
    BIMESTRE            SMALLINT        NOT NULL,
    TRIMESTRE           SMALLINT        NOT NULL,
    CUATRIMESTRE        SMALLINT        NOT NULL,
    SEMESTRE            SMALLINT        NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- ============================================================
-- BLOQUE 3: ESTRUCTURA ORGANIZACIONAL
-- ============================================================

CREATE TABLE DAGENCIA (
    PKAGENCIA           SERIAL          PRIMARY KEY,
    CODAGENCIA          CHAR(4)         NOT NULL UNIQUE,
    DESAGENCIA          VARCHAR(80)     NOT NULL,
    CODZONACOMERCIAL    CHAR(3)         NOT NULL,
    DESZONACOMERCIAL    VARCHAR(50)     NOT NULL,
    PKUBIGEO            INT             NOT NULL REFERENCES DUBIGEO(PKUBIGEO),
    LONGITUD            NUMERIC(10,7)   NULL,
    LATITUD             NUMERIC(10,7)   NULL,
    CODTIPOAGENCIA      CHAR(2)         NOT NULL,
    DESTIPOAGENCIA      VARCHAR(40)     NOT NULL,
    FECHAINICIOVIG      DATE            NOT NULL,
    FECHAFINVIG         DATE            NULL,
    FLAGACTIVO          CHAR(1)         NOT NULL DEFAULT '1',
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DJEFEREGIONAL (
    PKJEFEREGIONAL      SERIAL          PRIMARY KEY,
    CODJEFEREGIONAL     CHAR(6)         NOT NULL UNIQUE,
    NOMJEFEREGIONAL     VARCHAR(100)    NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DADMINISTRADOR (
    PKADMINISTRADOR     SERIAL          PRIMARY KEY,
    CODADMINISTRADOR    CHAR(6)         NOT NULL UNIQUE,
    NOMADMINISTRADOR    VARCHAR(100)    NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DASESOR (
    PKASESOR            SERIAL          PRIMARY KEY,
    CODASESOR           CHAR(6)         NOT NULL UNIQUE,
    NOMASESOR           VARCHAR(100)    NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DASESORNIVEL (
    PKASESORNIVEL       SERIAL          PRIMARY KEY,
    CODASESORNIVEL      CHAR(3)         NOT NULL UNIQUE,
    NOMASESORNIVEL      VARCHAR(40)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DCARGOPERSONAL (
    PKCARGOPERSONAL     SERIAL          PRIMARY KEY,
    CODCARGOPERSONAL    CHAR(3)         NOT NULL UNIQUE,
    DESCARGOPERSONAL    VARCHAR(80)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- Personal (planilla — consumido por core financiero y Power BI)
CREATE TABLE DPERSONAL (
    PKPERSONAL          SERIAL          PRIMARY KEY,
    CODPERSONAL         CHAR(6)         NOT NULL UNIQUE,
    NOMBRE              VARCHAR(100)    NOT NULL,
    SEXO                CHAR(1)         NOT NULL,
    NUMERODNI           CHAR(8)         NOT NULL,
    NUMERORUC           CHAR(11)        NULL,
    ESTADOCIVIL         CHAR(1)         NOT NULL,
    PROFESION           VARCHAR(60)     NULL,
    PKUBIGEO            INT             NULL REFERENCES DUBIGEO(PKUBIGEO),
    FECHAINGRESO        DATE            NOT NULL,
    FECHACESE           DATE            NULL,
    RELACIONINSTITUCION VARCHAR(30)     NOT NULL,
    ESTADOPERSONAL      CHAR(1)         NOT NULL DEFAULT '1',
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- ============================================================
-- BLOQUE 4: DIMENSION CLIENTE
-- ============================================================

CREATE TABLE DCLIENTE (
    PKCLIENTE                   SERIAL          PRIMARY KEY,
    CODCLIENTE                  CHAR(12)        NOT NULL UNIQUE,
    NOMCLIENTE                  VARCHAR(100)    NOT NULL,
    CODSBS                      CHAR(12)        NULL,
    PKCLASEPERSONA              INT             NOT NULL REFERENCES DCLASEPERSONA(PKCLASEPERSONA),
    CODCLASEPERSONA             CHAR(2)         NOT NULL,
    DESCLASEPERSONA             VARCHAR(40)     NOT NULL,
    FECHAINGRESOCAJA            DATE            NOT NULL,
    FECHAINICIOSISTEMAFIN       DATE            NULL,
    EMAIL                       VARCHAR(100)    NULL,
    PKACTIVIDADECONOMICA        INT             NULL REFERENCES DACTIVIDADECONOMICA(PKACTIVIDADECONOMICA),
    PKTIPODOCUMENTOIDENTIDAD    INT             NOT NULL REFERENCES DTIPODOCUMENTOIDENTIDAD(PKTIPODOCUMENTOIDENTIDAD),
    CODTIPODOCUMENTOIDENTIDAD   CHAR(2)         NOT NULL,
    DESTIPODOCUMENTOIDENTIDAD   VARCHAR(40)     NOT NULL,
    NUMERODOCUMENTOIDENTIDAD    VARCHAR(12)     NOT NULL,
    RUC                         CHAR(11)        NULL,
    NUMEROTELEFONOPERSONAL      VARCHAR(15)     NULL,
    MONTODEINGRESO              NUMERIC(14,4)   NULL,
    FECHANACIMIENTO             DATE            NULL,
    CODPAISNACIMIENTO           CHAR(3)         NULL,
    CODDEPARTAMENTONACIMIENTO   CHAR(2)         NULL,
    CODPROVINCIANACIMIENTO      CHAR(4)         NULL,
    CODDISTRITONACIMIENTO       CHAR(6)         NULL,
    CODZONANACIMIENTO           CHAR(4)         NULL,
    SEXO                        CHAR(1)         NULL,
    ESTADOCIVIL                 CHAR(1)         NULL,
    PKUBIGEO                    INT             NULL REFERENCES DUBIGEO(PKUBIGEO),
    PKTIPOVIA                   INT             NULL REFERENCES DTIPOVIA(PKTIPOVIA),
    TELEFONO                    VARCHAR(15)     NULL,
    ANIORESIDENCIA              SMALLINT        NULL,
    TIPOFUENTEINGRESO           CHAR(2)         NULL,
    ANIOINICIOINGRESO           SMALLINT        NULL,
    FECHAINGRESO                DATE            NULL,
    MONTOINGRESONETO            NUMERIC(14,4)   NULL,
    PKACTIVIDADECONOMICAINGRESO INT             NULL REFERENCES DACTIVIDADECONOMICA(PKACTIVIDADECONOMICA),
    NOMBREEMPRESAINGRESO        VARCHAR(100)    NULL,
    DIRECCIONEMPRESAINGRESO     VARCHAR(200)    NULL,
    RUCEMPRESAINGRESO           CHAR(11)        NULL,
    PKUBIGEOEMPRESA             INT             NULL REFERENCES DUBIGEO(PKUBIGEO),
    PKTIPOVIAEMPRESA            INT             NULL REFERENCES DTIPOVIA(PKTIPOVIA),
    TELEFONOEMPRESAINGRESO      VARCHAR(15)     NULL,
    CODEMPLEADOR                CHAR(8)         NULL,
    PKPAIS                      INT             NULL REFERENCES DPAIS(PKPAIS),
    FECULTACTUALIZACION         TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- Historial de domicilios del cliente
CREATE TABLE FCLIENTEUBIGEO (
    PKCLIENTE           INT             NOT NULL REFERENCES DCLIENTE(PKCLIENTE),
    PKUBIGEO            INT             NOT NULL REFERENCES DUBIGEO(PKUBIGEO),
    PERIODOMES          INT             NOT NULL REFERENCES DTIEMPOMES(PERIODOMES),
    PKTIPOVIA           INT             NULL REFERENCES DTIPOVIA(PKTIPOVIA),
    NROREGISTRO         INT             NOT NULL DEFAULT 1,
    NRODIRECCION        SMALLINT        NULL,
    DIRECCION           VARCHAR(200)    NULL,
    DIRECCIONREF        VARCHAR(200)    NULL,
    CODTIPDOMICILIO     CHAR(2)         NULL,
    ANIORESIDENCIA      SMALLINT        NULL,
    NROTELEFONO         VARCHAR(15)     NULL,
    FLAGDIRPREDETERMINADA CHAR(1)       NOT NULL DEFAULT 'S',
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY (PKCLIENTE, PERIODOMES, NROREGISTRO)
);

-- Historial de fuentes de ingreso del cliente
CREATE TABLE FCLIENTEFUENTEINGRESO (
    PKCLIENTE                   INT             NOT NULL REFERENCES DCLIENTE(PKCLIENTE),
    PERIODOMES                  INT             NOT NULL REFERENCES DTIEMPOMES(PERIODOMES),
    CODINTERNOFUENTEINGRESO     CHAR(3)         NULL,
    CODEMPLEADOR                CHAR(8)         NULL,
    TIPOFUENTEINGRESO           CHAR(2)         NULL,
    MONTOFUENTEINGRESO          NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CODRELACION                 CHAR(2)         NULL,
    ANIOINICIOFUENTEINGRESO     SMALLINT        NULL,
    NROEMPLEADOSEMPRESA         INT             NULL,
    CONDICIONCONTRATO           CHAR(2)         NULL,
    PKACTIVIDADECONOMICACLIENTE INT             NULL REFERENCES DACTIVIDADECONOMICA(PKACTIVIDADECONOMICA),
    NOMBREEMPRESA               VARCHAR(100)    NULL,
    NRODOCEMPRESA               VARCHAR(12)     NULL,
    PKUBIGEOEMPRESA             INT             NULL REFERENCES DUBIGEO(PKUBIGEO),
    NROTELEFONOEMPRESA          VARCHAR(15)     NULL,
    FECULTACTUALIZACION         TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY (PKCLIENTE, PERIODOMES)
);

-- ============================================================
-- BLOQUE 5: DIMENSIONES DE CREDITO
-- ============================================================

CREATE TABLE DPRODUCTO (
    PKPRODUCTO          SERIAL          PRIMARY KEY,
    CODTIPOCREDITO      CHAR(2)         NOT NULL,
    CODPRODUCTO         CHAR(2)         NOT NULL,
    CODSUBPRODUCTO      CHAR(2)         NOT NULL,
    DESTIPOCREDITO      VARCHAR(50)     NOT NULL,
    DESPRODUCTO         VARCHAR(60)     NOT NULL,
    DESSUBPRODUCTO      VARCHAR(60)     NOT NULL,
    DESSUBTIPOPRODUCTO  VARCHAR(60)     NULL,
    FECHAINICIOVIG      DATE            NOT NULL,
    FECHAFINVIG         DATE            NULL,
    FLAGACTIVO          CHAR(1)         NOT NULL DEFAULT '1',
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW(),
    UNIQUE (CODTIPOCREDITO, CODPRODUCTO, CODSUBPRODUCTO)
);

CREATE TABLE DMODALIDAD (
    PKMODALIDAD         SERIAL          PRIMARY KEY,
    CODMODALIDAD        CHAR(2)         NOT NULL UNIQUE,
    DESMODALIDAD        VARCHAR(40)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DTIPOTASA (
    PKTIPOTASA          SERIAL          PRIMARY KEY,
    CODTIPOTASA         CHAR(2)         NOT NULL UNIQUE,
    DESTIPOTASA         VARCHAR(40)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DGRUPOCREDITO (
    PKGRUPOCREDITO      SERIAL          PRIMARY KEY,
    CODGRUPOCREDITO     CHAR(2)         NOT NULL UNIQUE,
    DESGRUPOCREDITO     VARCHAR(40)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DESTADOCREDITO (
    PKESTADOCREDITO     SERIAL          PRIMARY KEY,
    CODESTADOCREDITO    CHAR(2)         NOT NULL UNIQUE,
    DESESTADOCREDITO    VARCHAR(40)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DCONDICIONCONTABLE (
    PKCONDICIONCONTABLE SERIAL          PRIMARY KEY,
    CODCONDICIONCONTABLE CHAR(2)        NOT NULL UNIQUE,
    DESCONDICIONCONTABLE VARCHAR(50)    NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DCALIFICACIONCREDITICIA (
    PKCALIFICACIONCREDITICIA  SERIAL    PRIMARY KEY,
    CODCALIFICACIONCREDITICIA CHAR(2)   NOT NULL UNIQUE,
    DESCALIFICACIONCREDITICIA VARCHAR(40) NOT NULL,
    FECULTACTUALIZACION       TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE DRECURSO (
    PKRECURSO           SERIAL          PRIMARY KEY,
    CODRECURSO          CHAR(3)         NOT NULL UNIQUE,
    DESRECURSO          VARCHAR(60)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DSUBRECURSO (
    PKSUBRECURSO        SERIAL          PRIMARY KEY,
    CODSUBRECURSO       CHAR(5)         NOT NULL UNIQUE,
    DESSUBRECURSO       VARCHAR(60)     NOT NULL,
    PKRECURSO           INT             NOT NULL REFERENCES DRECURSO(PKRECURSO),
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DNIVELAPROBACION (
    PKNIVELAPROBACION   SERIAL          PRIMARY KEY,
    CODNIVELAPROBACION  CHAR(2)         NOT NULL UNIQUE,
    DESNIVELAPROBACION  VARCHAR(50)     NOT NULL,
    MONTOMINIMO         NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOMAXIMO         NUMERIC(14,4)   NOT NULL DEFAULT 9999999999,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DCOMITE (
    PKCOMITE            SERIAL          PRIMARY KEY,
    CODCOMITE           CHAR(2)         NOT NULL UNIQUE,
    DESCOMITE           VARCHAR(60)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DCANALDESEMBOLSO (
    PKCANALDESEMBOLSO   SERIAL          PRIMARY KEY,
    CODCANALDESEMBOLSO  CHAR(2)         NOT NULL UNIQUE,
    DESCANALDESEMBOLSO  VARCHAR(40)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DADEUDADO (
    PKADEUDADO          SERIAL          PRIMARY KEY,
    CODADEUDADO         CHAR(2)         NOT NULL UNIQUE,
    DESADEUDADO         VARCHAR(40)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DGARANTIA (
    PKGARANTIA          SERIAL          PRIMARY KEY,
    CODTIPOGARANTIA     CHAR(3)         NOT NULL,
    DESTIPOGARANTIA     VARCHAR(50)     NOT NULL,
    CODCLASE            CHAR(3)         NOT NULL,
    DESCLASE            VARCHAR(50)     NOT NULL,
    CODTIPOCLASE        CHAR(3)         NULL,
    DESTIPOCLASE        VARCHAR(50)     NULL,
    CODSUBTIPOCLASE     CHAR(4)         NULL,
    DESSUBTIPOCLASE     VARCHAR(50)     NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DMODALIDADPAGO (
    PKMODALIDADPAGO     SERIAL          PRIMARY KEY,
    CODMODALIDADPAGO    CHAR(2)         NOT NULL UNIQUE,
    DESMODALIDADPAGO    VARCHAR(40)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DESTADODESEMBOLSO (
    PKESTADODESEMBOLSO  SERIAL          PRIMARY KEY,
    CODESTADODESEMBOLSO CHAR(2)         NOT NULL UNIQUE,
    DESESTADODESEMBOLSO VARCHAR(40)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- ============================================================
-- BLOQUE 6: SOLICITUD Y EVALUACION
-- ============================================================

CREATE TABLE DSOLICITUDESTADO (
    PKSOLICITUDESTADO   SERIAL          PRIMARY KEY,
    CODSOLICITUDESTADO  CHAR(2)         NOT NULL UNIQUE,
    DESSOLICITUDESTADO  VARCHAR(50)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DSOLICITUDSITUACION (
    PKSOLICITUDSITUACION SERIAL         PRIMARY KEY,
    CODSOLICITUDSITUACION CHAR(2)       NOT NULL UNIQUE,
    DESSOLICITUDSITUACION VARCHAR(50)   NOT NULL,
    FECULTACTUALIZACION  TIMESTAMP      NOT NULL DEFAULT NOW()
);

CREATE TABLE DSOLICITUD (
    PKSOLICITUD                 SERIAL          PRIMARY KEY,
    CODSOLICITUD                VARCHAR(20)     NOT NULL UNIQUE,
    PKCLIENTE                   INT             NOT NULL REFERENCES DCLIENTE(PKCLIENTE),
    CODEXPEDIENTE               VARCHAR(20)     NULL,
    PKSOLICITUDESTADO           INT             NOT NULL REFERENCES DSOLICITUDESTADO(PKSOLICITUDESTADO),
    CODLINEACREDITO             CHAR(3)         NULL,
    PKSOLICITUDSITUACION        INT             NULL REFERENCES DSOLICITUDSITUACION(PKSOLICITUDSITUACION),
    PKMONEDA                    INT             NOT NULL REFERENCES DMONEDA(PKMONEDA),
    PKGRUPOCREDITO              INT             NULL REFERENCES DGRUPOCREDITO(PKGRUPOCREDITO),
    PKNIVELAPROBACION           INT             NULL REFERENCES DNIVELAPROBACION(PKNIVELAPROBACION),
    PKCOMITE                    INT             NULL REFERENCES DCOMITE(PKCOMITE),
    PKPRODUCTO                  INT             NOT NULL REFERENCES DPRODUCTO(PKPRODUCTO),
    PKRECURSO                   INT             NULL REFERENCES DRECURSO(PKRECURSO),
    PKSUBRECURSO                INT             NULL REFERENCES DSUBRECURSO(PKSUBRECURSO),
    PKMODALIDAD                 INT             NULL REFERENCES DMODALIDAD(PKMODALIDAD),
    PKCANALDESEMBOLSO           INT             NULL REFERENCES DCANALDESEMBOLSO(PKCANALDESEMBOLSO),
    CODTIPOSOLICITUD            CHAR(2)         NULL,
    DESTIPOSOLICITUD            VARCHAR(40)     NULL,
    CODMOTIVOSOLICITUD          CHAR(2)         NULL,
    DESMOTIVOSOLICITUD          VARCHAR(80)     NULL,
    MONTOSOLICITUDCREDITO       NUMERIC(14,4)   NOT NULL,
    NROCUOTASOLICITUD           INT             NOT NULL,
    PLAZOSOLICITUDCREDITO       INT             NOT NULL,
    FECHASOLICITUDCREDITO       DATE            NOT NULL,
    CODUSUSOL                   CHAR(6)         NULL,
    MONTOAPROBADOCREDITO        NUMERIC(14,4)   NULL,
    NROCUOTAAPROBADO            INT             NULL,
    NRODIASGRACIA               INT             NOT NULL DEFAULT 0,
    DIAFECHAFIJA                SMALLINT        NULL,
    PLAZOAPROBADOCREDITO        INT             NULL,
    CODTIPOPERIODO              CHAR(2)         NULL,
    DESTIPOPERIODO              VARCHAR(30)     NULL,
    CODTIPOCUOTA                CHAR(2)         NULL,
    DESTIPOCUOTA                VARCHAR(30)     NULL,
    FLAGLIBREAMORTIZACIONCREDITO CHAR(1)        NOT NULL DEFAULT 'N',
    FECHAAPROBACIONCREDITO      DATE            NULL,
    NROTASACOMPENSATORIA        CHAR(6)         NULL,
    TASAINTERESCOMPENSATORIA    NUMERIC(10,6)   NULL,
    NROTASAMORATORIA            CHAR(6)         NULL,
    TASAINTERESMORATORIA        NUMERIC(10,6)   NULL,
    CODUSUING                   CHAR(6)         NULL,
    NRODIASGRACIAAPROBADO       INT             NOT NULL DEFAULT 0,
    CODTIPOCLIENTE              CHAR(2)         NULL,
    PKTIPOTASACOMPENSATORIA     INT             NULL REFERENCES DTIPOTASA(PKTIPOTASA),
    PKTIPOTASAMORATORIA         INT             NULL REFERENCES DTIPOTASA(PKTIPOTASA),
    PKACTIVIDADECONOMICASOLICITUD INT           NULL REFERENCES DACTIVIDADECONOMICA(PKACTIVIDADECONOMICA),
    PKADEUDADO                  INT             NULL REFERENCES DADEUDADO(PKADEUDADO),
    PKAGENCIA                   INT             NOT NULL REFERENCES DAGENCIA(PKAGENCIA),
    PKJEFEREGIONAL              INT             NULL REFERENCES DJEFEREGIONAL(PKJEFEREGIONAL),
    PKADMINISTRADOR             INT             NULL REFERENCES DADMINISTRADOR(PKADMINISTRADOR),
    PKASESOR                    INT             NOT NULL REFERENCES DASESOR(PKASESOR),
    PKASESORNIVEL               INT             NULL REFERENCES DASESORNIVEL(PKASESORNIVEL),
    FECHAHORACREACION           TIMESTAMP       NOT NULL DEFAULT NOW(),
    FECHAHORAULTMODIFICACION    TIMESTAMP       NOT NULL DEFAULT NOW(),
    FECULTACTUALIZACION         TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DEVALUACION (
    PKEVALUACION        SERIAL          PRIMARY KEY,
    NROEVALUACION       VARCHAR(20)     NOT NULL,
    VALOREXCEDENTECREDITO NUMERIC(14,4) NULL,
    TIPOEVALUACION      CHAR(2)         NOT NULL,  -- CO=Consumo, EM=Empresarial, AG=Agricola, MI=Micro
    CODSOLICITUD        VARCHAR(20)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- Evaluacion consumo
CREATE TABLE FEVALCONSUMO (
    PKEVALUACION        INT             NOT NULL REFERENCES DEVALUACION(PKEVALUACION),
    CODSECINGDEU        CHAR(3)         NULL,
    CODTIPOINGRESODEUDA CHAR(3)         NULL,
    DETALLEINGRESO      VARCHAR(100)    NULL,
    MONTO               NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CODRELACION         CHAR(2)         NULL,
    CODTIPOINGRESO      CHAR(2)         NULL,
    MONTOGASTOFAMILIAR  NUMERIC(14,4)   NOT NULL DEFAULT 0,
    FORTALEZAEVALUACION TEXT            NULL,
    DEBILIDADEVALUACION TEXT            NULL,
    GESTIONEVALUACION   TEXT            NULL,
    EVALUACIONCOMERCIALSUSTENTO TEXT    NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY (PKEVALUACION)
);

-- Evaluacion empresarial
CREATE TABLE FEVALEMPRESARIAL (
    PKEVALUACION        INT             NOT NULL REFERENCES DEVALUACION(PKEVALUACION),
    MONTOVENTA          NUMERIC(14,4)   NOT NULL DEFAULT 0,
    COSTOVENTAPRODUCTO  NUMERIC(14,4)   NOT NULL DEFAULT 0,
    UTILIDADBRUTA       NUMERIC(14,4)   NOT NULL DEFAULT 0,
    GASTOOPERATIVONEGOCIO NUMERIC(14,4) NOT NULL DEFAULT 0,
    GASTOSPERSONALES    NUMERIC(14,4)   NOT NULL DEFAULT 0,
    GASTOSSERVICIOS     NUMERIC(14,4)   NOT NULL DEFAULT 0,
    UTILIDADOPERATIVA   NUMERIC(14,4)   NOT NULL DEFAULT 0,
    OBLIGACIONNEGOCIO   NUMERIC(14,4)   NOT NULL DEFAULT 0,
    OBLIGACIONNETANEGOCIO NUMERIC(14,4) NOT NULL DEFAULT 0,
    OTRASFUENTESINGRESO NUMERIC(14,4)   NOT NULL DEFAULT 0,
    TOTALOBLIGACIONFAMILIAR NUMERIC(14,4) NOT NULL DEFAULT 0,
    GASTOSFAMILIARES    NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAPACIDADPAGO       NUMERIC(14,4)   NOT NULL DEFAULT 0,
    RESULTADOFUENTESINGRESO NUMERIC(14,4) NOT NULL DEFAULT 0,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY (PKEVALUACION)
);

-- Evaluacion micro (activos, pasivos, ingresos, costos)
CREATE TABLE FEVALMICROACTIVO (
    PKEVALUACION        INT             NOT NULL REFERENCES DEVALUACION(PKEVALUACION),
    NROREG              INT             NOT NULL,
    MONTOACTIVODISPONIBLE NUMERIC(14,4) NOT NULL DEFAULT 0,
    MONTOACTIVOINVENTARIO NUMERIC(14,4) NOT NULL DEFAULT 0,
    MONTOACTIVOFIJO     NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOGASTOFAMILIAR  NUMERIC(14,4)   NOT NULL DEFAULT 0,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY (PKEVALUACION, NROREG)
);

-- ============================================================
-- BLOQUE 7: CUENTA CREDITO Y CRONOGRAMA
-- ============================================================

CREATE TABLE DCUENTACREDITO (
    PKCUENTACREDITO     SERIAL          PRIMARY KEY,
    CODCUENTACREDITO    VARCHAR(18)     NOT NULL UNIQUE,
    CODLINEACREDITO     CHAR(3)         NULL,
    PKCLIENTE           INT             NOT NULL REFERENCES DCLIENTE(PKCLIENTE),
    NROCRONOGRAMA       INT             NOT NULL DEFAULT 1,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- Fact agregado mensual de crédito (tabla central del core financiero y Power BI)
CREATE TABLE FAGCUENTACREDITO (
    PERIODOMES                  INT             NOT NULL REFERENCES DTIEMPOMES(PERIODOMES),
    PKCUENTACREDITO             INT             NOT NULL REFERENCES DCUENTACREDITO(PKCUENTACREDITO),
    PKSOLICITUD                 INT             NULL REFERENCES DSOLICITUD(PKSOLICITUD),
    PKESTADOCREDITO             INT             NOT NULL REFERENCES DESTADOCREDITO(PKESTADOCREDITO),
    NROCUOTAS                   INT             NOT NULL,
    NRODIAS                     INT             NOT NULL DEFAULT 0,
    NRODIASGRACIAS              INT             NOT NULL DEFAULT 0,
    DIAFECHAFIJA                SMALLINT        NULL,
    CODTIPOCUOTA                CHAR(2)         NULL,
    CODTIPOPERIODO              CHAR(2)         NULL,
    FLAGLIBREAMORTIZACION       CHAR(1)         NOT NULL DEFAULT 'N',
    MONTOAPROBADOCREDITO        NUMERIC(14,4)   NOT NULL,
    MONTOCAPITALDESEMBOLSADO    NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOCAPITALPAGADO          NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOINTERESPROGRAMADO      NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOINTERESALAFECHA        NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOINTERESPAGADO          NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOMORAPROGRAMADA         NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOMORAPAGADA             NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOGASTOPROGRAMADO        NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOGASTOPAGADO            NUMERIC(14,4)   NOT NULL DEFAULT 0,
    PKPRODUCTO                  INT             NOT NULL REFERENCES DPRODUCTO(PKPRODUCTO),
    PKRECURSO                   INT             NULL REFERENCES DRECURSO(PKRECURSO),
    PKSUBRECURSO                INT             NULL REFERENCES DSUBRECURSO(PKSUBRECURSO),
    PKMONEDA                    INT             NOT NULL REFERENCES DMONEDA(PKMONEDA),
    PKMODALIDAD                 INT             NULL REFERENCES DMODALIDAD(PKMODALIDAD),
    CODPLAZO                    CHAR(3)         NULL,
    CODLINEACREDITO             CHAR(3)         NULL,
    NROTASACOMPENSATORIA        CHAR(6)         NULL,
    TASAINTERESCOMPENSATORIA    NUMERIC(10,6)   NOT NULL,
    NROTASAMORATORIA            CHAR(6)         NULL,
    TASAINTERESMORATORIA        NUMERIC(10,6)   NOT NULL,
    DIASATRASOCREDITO           INT             NOT NULL DEFAULT 0,
    FECHACULMINACIONCREDITO     DATE            NULL,
    FECHAGENERACIONCREDITO      DATE            NULL,
    FECHADESEMBOLSOCREDITO      DATE            NOT NULL,
    TIPOCAMBIODESEMBOLSO        NUMERIC(8,4)    NOT NULL DEFAULT 1,
    PKGRUPOCREDITO              INT             NULL REFERENCES DGRUPOCREDITO(PKGRUPOCREDITO),
    FLAGREFINANCIADO            CHAR(1)         NOT NULL DEFAULT 'N',
    FLAGREESTRUCTURADO          CHAR(1)         NOT NULL DEFAULT 'N',
    FLAGREPROGRAMADO            CHAR(1)         NOT NULL DEFAULT 'N',
    FLAGJUDICIAL                CHAR(1)         NOT NULL DEFAULT 'N',
    FLAGCASTIGADO               CHAR(1)         NOT NULL DEFAULT 'N',
    PKACTIVIDADECONOMICA        INT             NULL REFERENCES DACTIVIDADECONOMICA(PKACTIVIDADECONOMICA),
    MONTOSALDONORMAL            NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOSALDOVENCIDO           NUMERIC(14,4)   NOT NULL DEFAULT 0,
    FLAGNUEVORECURRENTE         CHAR(1)         NULL,
    MONTOCOSTOEFECTIVO          NUMERIC(10,6)   NULL,
    PKTIPOTASACOMPENSATORIA     INT             NULL REFERENCES DTIPOTASA(PKTIPOTASA),
    PKTIPOTASAMORATORIA         INT             NULL REFERENCES DTIPOTASA(PKTIPOTASA),
    PKCLIENTE                   INT             NOT NULL REFERENCES DCLIENTE(PKCLIENTE),
    NROCRONOGRAMA               INT             NOT NULL DEFAULT 1,
    PKCONDICIONCONTABLE         INT             NULL REFERENCES DCONDICIONCONTABLE(PKCONDICIONCONTABLE),
    FLAGCLIENTENUEVOBANCOANDINO CHAR(1)        NOT NULL DEFAULT 'N',
    FLAGCLIENTENUEVO            CHAR(1)         NOT NULL DEFAULT 'N',
    FLAGCLIENTECARTERA          CHAR(1)         NOT NULL DEFAULT 'N',
    PKCALIFICACIONCREDITICIAINTERNA INT         NULL REFERENCES DCALIFICACIONCREDITICIA(PKCALIFICACIONCREDITICIA),
    PKCALIFICACIONCREDITICIAEXTERNA INT         NULL REFERENCES DCALIFICACIONCREDITICIA(PKCALIFICACIONCREDITICIA),
    FECHAINGRESOJUDICIAL        DATE            NULL,
    MONTOCAPITALINICIO          NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOINTERESINICIO          NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOMORAINICIO             NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOGASTOINICIO            NUMERIC(14,4)   NOT NULL DEFAULT 0,
    NRODIASATRASOINICIO         INT             NOT NULL DEFAULT 0,
    -- Saldos calculados
    MONTOSALDOCAPITAL           NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOSALDOINTERES           NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOSALDOMORATORIO         NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOSALDOGASTO             NUMERIC(14,4)   NOT NULL DEFAULT 0,
    -- Cartera vigente
    CAR_VIG_CAPITAL             NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_VIG_INT_COMPENSATORIO   NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_VIG_INT_MORATORIO       NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_VIG_GASTOS              NUMERIC(14,4)   NOT NULL DEFAULT 0,
    -- Cartera vencida
    CAR_VEN_CAPITAL             NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_VEN_INT_COMPENSATORIO   NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_VEN_INT_MORATORIO       NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_VEN_GASTOS              NUMERIC(14,4)   NOT NULL DEFAULT 0,
    -- Cartera refinanciada
    CAR_REF_CAPITAL             NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_REF_INT_COMPENSATORIO   NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_REF_INT_MORATORIO       NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_REF_GASTOS              NUMERIC(14,4)   NOT NULL DEFAULT 0,
    -- Cartera reprogramada
    CAR_REP_CAPITAL             NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_REP_INT_COMPENSATORIO   NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_REP_INT_MORATORIO       NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_REP_GASTOS              NUMERIC(14,4)   NOT NULL DEFAULT 0,
    -- Cartera judicial
    CAR_JUD_CAPITAL             NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_JUD_INT_COMPENSATORIO   NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_JUD_INT_MORATORIO       NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_JUD_GASTOS              NUMERIC(14,4)   NOT NULL DEFAULT 0,
    -- Cartera castigada
    CAR_CAS_CAPITAL             NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_CAS_INT_COMPENSATORIO   NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_CAS_INT_MORATORIO       NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_CAS_GASTOS              NUMERIC(14,4)   NOT NULL DEFAULT 0,
    -- Cartera condonada
    CAR_CON_CAPITAL             NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_CON_INT_COMPENSATORIO   NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_CON_INT_MORATORIO       NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CAR_CON_GASTOS              NUMERIC(14,4)   NOT NULL DEFAULT 0,
    -- Provisiones y devengados
    SALDODIFERIDO               NUMERIC(14,4)   NOT NULL DEFAULT 0,
    SALDODEVENGADO              NUMERIC(14,4)   NOT NULL DEFAULT 0,
    SALDOPROVISIONES            NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOSALDOCLIENTE           NUMERIC(14,4)   NOT NULL DEFAULT 0,
    -- Gestión
    PKAGENCIA                   INT             NOT NULL REFERENCES DAGENCIA(PKAGENCIA),
    PKJEFEREGIONAL              INT             NULL REFERENCES DJEFEREGIONAL(PKJEFEREGIONAL),
    PKADMINISTRADOR             INT             NULL REFERENCES DADMINISTRADOR(PKADMINISTRADOR),
    PKASESOR                    INT             NOT NULL REFERENCES DASESOR(PKASESOR),
    PKASESORNIVEL               INT             NULL REFERENCES DASESORNIVEL(PKASESORNIVEL),
    FECULTACTUALIZACION         TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY (PERIODOMES, PKCUENTACREDITO)
);

-- Cronograma cuota a cuota (home banking: mis créditos / cuotas pendientes)
CREATE TABLE FPLANPAGOMES (
    PERIODOMES                  INT             NOT NULL REFERENCES DTIEMPOMES(PERIODOMES),
    PKCUENTACREDITO             INT             NOT NULL REFERENCES DCUENTACREDITO(PKCUENTACREDITO),
    CODPLANPAGO                 VARCHAR(15)     NOT NULL,
    NROCUOTA                    INT             NOT NULL,
    PKSOLICITUD                 INT             NULL REFERENCES DSOLICITUD(PKSOLICITUD),
    PKESTADOCREDITO             INT             NOT NULL REFERENCES DESTADOCREDITO(PKESTADOCREDITO),
    PKPRODUCTO                  INT             NOT NULL REFERENCES DPRODUCTO(PKPRODUCTO),
    PKMONEDA                    INT             NOT NULL REFERENCES DMONEDA(PKMONEDA),
    PKMODALIDAD                 INT             NULL REFERENCES DMODALIDAD(PKMODALIDAD),
    PKGRUPOCREDITO              INT             NULL REFERENCES DGRUPOCREDITO(PKGRUPOCREDITO),
    PKACTIVIDADECONOMICA        INT             NULL REFERENCES DACTIVIDADECONOMICA(PKACTIVIDADECONOMICA),
    PKTIPOTASACOMPENSATORIA     INT             NULL REFERENCES DTIPOTASA(PKTIPOTASA),
    PKTIPOTASAMORATORIA         INT             NULL REFERENCES DTIPOTASA(PKTIPOTASA),
    PKCLIENTE                   INT             NOT NULL REFERENCES DCLIENTE(PKCLIENTE),
    PKCONDICIONCONTABLE         INT             NULL REFERENCES DCONDICIONCONTABLE(PKCONDICIONCONTABLE),
    PKCALIFICACIONCREDITICIAINTERNA INT         NULL REFERENCES DCALIFICACIONCREDITICIA(PKCALIFICACIONCREDITICIA),
    PKAGENCIA                   INT             NOT NULL REFERENCES DAGENCIA(PKAGENCIA),
    PKJEFEREGIONAL              INT             NULL REFERENCES DJEFEREGIONAL(PKJEFEREGIONAL),
    PKADMINISTRADOR             INT             NULL REFERENCES DADMINISTRADOR(PKADMINISTRADOR),
    PKASESOR                    INT             NOT NULL REFERENCES DASESOR(PKASESOR),
    PKASESORNIVEL               INT             NULL REFERENCES DASESORNIVEL(PKASESORNIVEL),
    PKESTADODESEMBOLSO          INT             NULL REFERENCES DESTADODESEMBOLSO(PKESTADODESEMBOLSO),
    PKMODALIDADPAGO             INT             NULL REFERENCES DMODALIDADPAGO(PKMODALIDADPAGO),
    CODESTADOCUOTA              CHAR(2)         NOT NULL DEFAULT 'PE',  -- PE=Pendiente,PA=Pagado,VE=Vencido
    CODESTADOPLAN               CHAR(2)         NULL,
    FECHAVENCIMIENTOPAGOCUOTA   DATE            NOT NULL,
    FECHAPAGOCUOTA              DATE            NULL,
    MONTOCUOTA                  NUMERIC(14,4)   NOT NULL,
    MONTOSALDO                  NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOMORA                   NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOCUOTAVENCIDA           NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOCUOTAATRASADA          NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOINTERESPROGRAMADO      NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOINTERESPAGADO          NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOINTERESALAFECHA        NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOMORAPROGRAMADO         NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOMORAPAGADA             NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOGASTO                  NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOGASTOPROGRAMADO        NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOGASTOPAGADO            NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOSALDOCAPITAL           NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOCAPITALPAGADO          NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOCAPITALPROGRAMADO      NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOCAPITALDESEMBOLSADO    NUMERIC(14,4)   NOT NULL DEFAULT 0,
    DIASATRASOCUOTA             INT             NOT NULL DEFAULT 0,
    DIASVENCIDOCUOTA            INT             NOT NULL DEFAULT 0,
    INTERESDEVENGADOCUOTA       NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOPAGOANTICIPADO         NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOPAGOPARCIAL            NUMERIC(14,4)   NOT NULL DEFAULT 0,
    FECULTACTUALIZACION         TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY (PERIODOMES, PKCUENTACREDITO, NROCUOTA)
);

-- Garantías del crédito
CREATE TABLE FGARANTIAS (
    PKCUENTACREDITO             INT             NOT NULL REFERENCES DCUENTACREDITO(PKCUENTACREDITO),
    PKGARANTIA                  INT             NOT NULL REFERENCES DGARANTIA(PKGARANTIA),
    PKCLIENTE                   INT             NOT NULL REFERENCES DCLIENTE(PKCLIENTE),
    CODLINEACREDITO             CHAR(3)         NULL,
    CODSECUENCIAGARANTIA        SMALLINT        NOT NULL DEFAULT 1,
    FECHAREGISTROGARANTIA       DATE            NOT NULL,
    MONTOORIGENGARANTIA         NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOGRAVAMENGARANTIA       NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CODRELACIONCUENTA           CHAR(2)         NULL,
    MONTOTASACIONGARANTIADOLARES NUMERIC(14,4)  NOT NULL DEFAULT 0,
    TIPOCAMBIOGARANTIA          NUMERIC(8,4)    NOT NULL DEFAULT 1,
    PORCCOBERTURAGARANTIA       NUMERIC(8,4)    NOT NULL DEFAULT 0,
    PORCLINEACOBERTURAGARANTIA  NUMERIC(8,4)    NOT NULL DEFAULT 0,
    MONTOGRAVAMENGARANTIASOLES  NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOGARANTIAORIGENSOLES    NUMERIC(14,4)   NOT NULL DEFAULT 0,
    VALORMERCADOGARANTIASOLES   NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOTASACIONGARANTIASOLES  NUMERIC(14,4)   NOT NULL DEFAULT 0,
    FECULTACTUALIZACION         TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY (PKCUENTACREDITO, PKGARANTIA, CODSECUENCIAGARANTIA)
);

-- ============================================================
-- BLOQUE 8: DIMENSIONES AHORROS
-- ============================================================

CREATE TABLE DPRODUCTOAHORRO (
    PKPRODUCTOAHORRO    SERIAL          PRIMARY KEY,
    CODTIPOPRODUCTO     CHAR(2)         NOT NULL,
    CODTIPOSUBPRODUCTO  CHAR(2)         NOT NULL,
    CODCARACTERISTICA   CHAR(3)         NOT NULL,
    DESTIPOPRODUCTO     VARCHAR(60)     NOT NULL,
    DESTIPOSUBPRODUCTO  VARCHAR(60)     NOT NULL,
    DESCARACTERISTICA   VARCHAR(60)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW(),
    UNIQUE (CODTIPOPRODUCTO, CODTIPOSUBPRODUCTO, CODCARACTERISTICA)
);

CREATE TABLE DTIPOCUENTAAHORRO (
    PKTIPOCUENTAAHORRO  SERIAL          PRIMARY KEY,
    CODTIPOCUENTAAHORRO CHAR(2)         NOT NULL UNIQUE,
    DESTIPOCUENTAAHORRO VARCHAR(40)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DTIPOTASAAHORRO (
    PKTIPOTASAAHORRO    SERIAL          PRIMARY KEY,
    CODTIPOTASAAHORRO   CHAR(2)         NOT NULL UNIQUE,
    DESTIPOTASAAHORRO   VARCHAR(40)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DESTADOCUENTA (
    PKESTADOCUENTA      SERIAL          PRIMARY KEY,
    CODESTADOCUENTA     CHAR(2)         NOT NULL UNIQUE,
    DESESTADOCUENTA     VARCHAR(40)     NOT NULL,
    ESTADO              CHAR(1)         NOT NULL DEFAULT '1',
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DAUXILIAR (
    PKAUXILIAR          SERIAL          PRIMARY KEY,
    CODAUXILIAR         CHAR(6)         NOT NULL UNIQUE,
    NOMAUXILIAR         VARCHAR(80)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DOPERADOR (
    PKOPERADOR          SERIAL          PRIMARY KEY,
    CODOPERADOR         CHAR(4)         NOT NULL UNIQUE,
    NOMOPERADOR         VARCHAR(60)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- ============================================================
-- BLOQUE 9: CUENTA AHORRO Y PRODUCTOS PASIVOS
-- ============================================================

CREATE TABLE DCUENTAAHORRO (
    PKCUENTAAHORRO      SERIAL          PRIMARY KEY,
    CODCUENTAAHORRO     VARCHAR(20)     NOT NULL UNIQUE,
    PKCLIENTE           INT             NOT NULL REFERENCES DCLIENTE(PKCLIENTE),
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- Fact diario de cuenta ahorro (home banking: saldo disponible, movimientos)
CREATE TABLE FCUENTAAHORRO (
    PERIODODIA                  INT             NOT NULL REFERENCES DTIEMPO(PERIODODIA),
    PKCUENTAAHORRO              INT             NOT NULL REFERENCES DCUENTAAHORRO(PKCUENTAAHORRO),
    PKPRODUCTOAHORRO            INT             NOT NULL REFERENCES DPRODUCTOAHORRO(PKPRODUCTOAHORRO),
    PKMONEDA                    INT             NOT NULL REFERENCES DMONEDA(PKMONEDA),
    PKTIPOCUENTAAHORRO          INT             NOT NULL REFERENCES DTIPOCUENTAAHORRO(PKTIPOCUENTAAHORRO),
    PKTIPOTASAAHORRO            INT             NULL REFERENCES DTIPOTASAAHORRO(PKTIPOTASAAHORRO),
    PKCLIENTE                   INT             NOT NULL REFERENCES DCLIENTE(PKCLIENTE),
    PKAUXILIAR                  INT             NULL REFERENCES DAUXILIAR(PKAUXILIAR),
    PKOPERADOR                  INT             NULL REFERENCES DOPERADOR(PKOPERADOR),
    PKADMINISTRADOR             INT             NULL REFERENCES DADMINISTRADOR(PKADMINISTRADOR),
    PKJEFEREGIONAL              INT             NULL REFERENCES DJEFEREGIONAL(PKJEFEREGIONAL),
    PKAGENCIA                   INT             NOT NULL REFERENCES DAGENCIA(PKAGENCIA),
    PKESTADOCUENTA              INT             NOT NULL REFERENCES DESTADOCUENTA(PKESTADOCUENTA),
    TIPOCAMBIO                  NUMERIC(8,4)    NOT NULL DEFAULT 1,
    MONTOSALDOCAPITALTOTAL      NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOSALDOINTERESTOTAL      NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOSALDOPROMEDIOTOTAL     NUMERIC(14,4)   NOT NULL DEFAULT 0,
    FECHAAPERTURACUENTA         DATE            NOT NULL,
    MONTODEPOSITOAPERTURA       NUMERIC(14,4)   NOT NULL DEFAULT 0,
    TASAINTERESCUENTA           NUMERIC(10,6)   NOT NULL DEFAULT 0,
    TASAEFECTIVAANUAL           NUMERIC(10,6)   NOT NULL DEFAULT 0,
    NROTITULARES                SMALLINT        NOT NULL DEFAULT 1,
    NROFIRMAS                   SMALLINT        NOT NULL DEFAULT 1,
    FLAGEXONERACIONIMPUESTO     CHAR(1)         NOT NULL DEFAULT 'N',
    FLAGEXONERACIONCOMISION     CHAR(1)         NOT NULL DEFAULT 'N',
    FLAGCUENTAPROMOCION         CHAR(1)         NOT NULL DEFAULT 'N',
    NROOPERACIONESLIBRES        INT             NOT NULL DEFAULT 0,
    FECHAULTIMACONSULTA         TIMESTAMP       NULL,
    -- Ahorro corriente (_AC)
    FLAG_AC                     CHAR(1)         NOT NULL DEFAULT 'N',
    MONTOSALDODISPONIBLE_AC     NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOSALDOMINIMO_AC         NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOSALDOCONTABLE_AC       NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOINTERESACUANTCAP_AC    NUMERIC(14,4)   NOT NULL DEFAULT 0,
    NROOPERACIONES_AC           INT             NOT NULL DEFAULT 0,
    -- Plazo fijo (_PF)
    FLAG_PF                     CHAR(1)         NOT NULL DEFAULT 'N',
    FECHAVIGENCIA_PF            DATE            NULL,
    MONTOSALDOCAPITAL_PF        NUMERIC(14,4)   NOT NULL DEFAULT 0,
    NRODIASPLAZOFIJO_PF         INT             NOT NULL DEFAULT 0,
    MONTOINTERESPACTADO_PF      NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOINTERESPAGADO_PF       NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOINTERESDEVENGADO_PF    NUMERIC(14,4)   NOT NULL DEFAULT 0,
    TASAPAGADA_PF               NUMERIC(10,6)   NOT NULL DEFAULT 0,
    NUMERORENOVACION_PF         INT             NOT NULL DEFAULT 0,
    -- CTS (_CTS)
    FLAG_CTS                    CHAR(1)         NOT NULL DEFAULT 'N',
    MONTOCAPITAL_CTS            NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOINTERES_CTS            NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOCAPITALINTANGIBLE_CTS  NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOINTERESINTANGIBLE_CTS  NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CODEMPLEADOR_CTS            CHAR(8)         NULL,
    CODBANCOORIGENTRASLADO_CTS  CHAR(4)         NULL,
    CODBANCODESTINOTRASLADO_CTS CHAR(4)         NULL,
    -- Ahorro programado (_AP)
    FLAG_AP                     CHAR(1)         NOT NULL DEFAULT 'N',
    MONTOCAPITAL_AP             NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOCUOTA_AP               NUMERIC(14,4)   NOT NULL DEFAULT 0,
    NROCUOTA_AP                 INT             NOT NULL DEFAULT 0,
    TASAINCENTIVO_AP            NUMERIC(10,6)   NOT NULL DEFAULT 0,
    FECHAVIGENCIA_AP            DATE            NULL,
    FECULTACTUALIZACION         TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY (PERIODODIA, PKCUENTAAHORRO)
);

-- Cuotas de ahorro programado
CREATE TABLE FCUENTAAHORROPROGRAMADO (
    PKCUENTAAHORRO      INT             NOT NULL REFERENCES DCUENTAAHORRO(PKCUENTAAHORRO),
    CODDEPOSITO         VARCHAR(15)     NOT NULL,
    FECHADEPOSITOCUOTA  DATE            NOT NULL,
    FECHAEFECTUADOCUOTA DATE            NULL,
    MONTOCUOTA          NUMERIC(14,4)   NOT NULL,
    NRODIASRETRAZO      INT             NOT NULL DEFAULT 0,
    MONTOAMORTIZADO     NUMERIC(14,4)   NOT NULL DEFAULT 0,
    CODESTADOCUOTA      CHAR(2)         NOT NULL DEFAULT 'PE',
    NRORENOVACIONES     INT             NOT NULL DEFAULT 0,
    MONTOINCENTIVOINICIAL NUMERIC(14,4) NOT NULL DEFAULT 0,
    MONTOINCENTIVOFINAL NUMERIC(14,4)   NOT NULL DEFAULT 0,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY (PKCUENTAAHORRO, CODDEPOSITO)
);

-- Titularidad múltiple de cuentas ahorro
CREATE TABLE FCUENTAAHORROMULTIPLE (
    PERIODODIA          INT             NOT NULL REFERENCES DTIEMPO(PERIODODIA),
    PKCUENTAAHORRO      INT             NOT NULL REFERENCES DCUENTAAHORRO(PKCUENTAAHORRO),
    PKCLIENTE           INT             NOT NULL REFERENCES DCLIENTE(PKCLIENTE),
    FLAGPRESTRANSACCION CHAR(1)         NOT NULL DEFAULT 'N',
    CODRELACIONCUENTA   CHAR(2)         NULL,
    FLAGCONESTCLI       CHAR(1)         NOT NULL DEFAULT 'N',
    FLAGESTADOCUENTA    CHAR(1)         NOT NULL DEFAULT '1',
    FLAGRESPONSABLEIMPUESTO CHAR(1)     NOT NULL DEFAULT 'N',
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY (PERIODODIA, PKCUENTAAHORRO, PKCLIENTE)
);

-- ============================================================
-- BLOQUE 10: OPERACIONES / TRANSFERENCIAS / PAGOS
-- ============================================================

CREATE TABLE DCONCEPTOOPERACION (
    PKCONCEPTOOPERACION SERIAL          PRIMARY KEY,
    CODCONCEPTOOPERACION CHAR(4)        NOT NULL UNIQUE,
    DESCONCEPTOOPERACION VARCHAR(80)    NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DTIPOOPERACION (
    PKTIPOOPERACION     SERIAL          PRIMARY KEY,
    CODTIPOOPERACION    CHAR(3)         NOT NULL UNIQUE,
    DESTIPOOPERACION    VARCHAR(50)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DMEDIOPAGO (
    PKMEDIOPAGO         SERIAL          PRIMARY KEY,
    CODMEDIOPAGO        CHAR(3)         NOT NULL UNIQUE,
    DESMEDIOPAGO        VARCHAR(40)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DCANALTRANSACCIONAL (
    PKCANALTRANSACCIONAL SERIAL         PRIMARY KEY,
    CODCANALTRANSACCIONAL CHAR(3)       NOT NULL UNIQUE,
    DESCANALTRANSACCIONAL VARCHAR(50)   NOT NULL,
    FECULTACTUALIZACION  TIMESTAMP      NOT NULL DEFAULT NOW()
);

-- Kardex unificado crédito + ahorro (home banking: estado de cuenta / movimientos)
CREATE TABLE FOPERACIONES (
    PKOPERACION         BIGSERIAL       PRIMARY KEY,
    CODTIPKAR           CHAR(2)         NOT NULL,
    PKCUENTACREDITO     INT             NULL REFERENCES DCUENTACREDITO(PKCUENTACREDITO),
    PKCUENTAAHORRO      INT             NULL REFERENCES DCUENTAAHORRO(PKCUENTAAHORRO),
    CODKARDEX           VARCHAR(20)     NOT NULL,
    PKCONCEPTOOPERACION INT             NOT NULL REFERENCES DCONCEPTOOPERACION(PKCONCEPTOOPERACION),
    NROCUOTAPLAZO       INT             NULL,
    CODSECKAR           CHAR(4)         NULL,
    FECHAHORAOPERACION  TIMESTAMP       NOT NULL,
    PERIODODIA          INT             NOT NULL REFERENCES DTIEMPO(PERIODODIA),
    PKTIPOOPERACION     INT             NOT NULL REFERENCES DTIPOOPERACION(PKTIPOOPERACION),
    PKMEDIOPAGO         INT             NULL REFERENCES DMEDIOPAGO(PKMEDIOPAGO),
    PKMONEDA            INT             NOT NULL REFERENCES DMONEDA(PKMONEDA),
    PKCONDICIONCONTABLE INT             NULL REFERENCES DCONDICIONCONTABLE(PKCONDICIONCONTABLE),
    PKPRODUCTO          INT             NULL REFERENCES DPRODUCTO(PKPRODUCTO),
    PKPRODUCTOAHORRO    INT             NULL REFERENCES DPRODUCTOAHORRO(PKPRODUCTOAHORRO),
    PKRECURSO           INT             NULL REFERENCES DRECURSO(PKRECURSO),
    PKSUBRECURSO        INT             NULL REFERENCES DSUBRECURSO(PKSUBRECURSO),
    PKAGENCIAORIGEN     INT             NOT NULL REFERENCES DAGENCIA(PKAGENCIA),
    PKAGENCIADESTINO    INT             NULL REFERENCES DAGENCIA(PKAGENCIA),
    PKCANALTRANSACCIONAL INT            NULL REFERENCES DCANALTRANSACCIONAL(PKCANALTRANSACCIONAL),
    CODTIPOEGRESOINGRESO CHAR(1)        NOT NULL,  -- E=Egreso, I=Ingreso
    CODUSUOPE           CHAR(6)         NULL,
    MONTOPAGOCONCEPTO   NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOOPERACION      NUMERIC(14,4)   NOT NULL DEFAULT 0,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- Convenios / Pagos de servicios (home banking: pagar servicios)
CREATE TABLE DCONVENIO (
    PKCONVENIO          SERIAL          PRIMARY KEY,
    PKCLIENTE           INT             NULL REFERENCES DCLIENTE(PKCLIENTE),
    CODSERVICIO         VARCHAR(10)     NOT NULL,
    DESEMPRESA          VARCHAR(80)     NOT NULL,
    DESSERVICIO         VARCHAR(80)     NOT NULL,
    CODESTADO           CHAR(1)         NOT NULL DEFAULT '1',
    CODSUCURSAL         VARCHAR(10)     NULL,
    CODCONCEPTO         VARCHAR(10)     NULL,
    DESSUCURSAL         VARCHAR(60)     NULL,
    DESCONCEPTO         VARCHAR(60)     NULL,
    CODCATEGORIA        CHAR(3)         NULL,
    DESCATEGORIA        VARCHAR(40)     NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DDEBITOAUTOMATICO (
    PKDEBITOAUTOMATICO  SERIAL          PRIMARY KEY,
    CODDEBITOAUTOMATICO CHAR(3)         NOT NULL UNIQUE,
    DESDEBITOAUTOMATICO VARCHAR(50)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DCANALGIRO (
    PKCANALGIRO         SERIAL          PRIMARY KEY,
    CODCANALGIRO        CHAR(3)         NOT NULL UNIQUE,
    DESCANALGIRO        VARCHAR(50)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE FCONVENIO (
    PKFCONVENIO             BIGSERIAL       PRIMARY KEY,
    PERIODODIAKARDEX        INT             NOT NULL REFERENCES DTIEMPO(PERIODODIA),
    CODCLIENTECONVENIO      VARCHAR(20)     NOT NULL,
    PERIODOPAGO             INT             NOT NULL,
    PKCONVENIO              INT             NOT NULL REFERENCES DCONVENIO(PKCONVENIO),
    PKMONEDA                INT             NOT NULL REFERENCES DMONEDA(PKMONEDA),
    PKAUXILIAR              INT             NULL REFERENCES DAUXILIAR(PKAUXILIAR),
    PKOPERADOR              INT             NULL REFERENCES DOPERADOR(PKOPERADOR),
    PKAGENCIA               INT             NOT NULL REFERENCES DAGENCIA(PKAGENCIA),
    PKDEBITOAUTOMATICO      INT             NULL REFERENCES DDEBITOAUTOMATICO(PKDEBITOAUTOMATICO),
    PKCANALGIRO             INT             NULL REFERENCES DCANALGIRO(PKCANALGIRO),
    CODESTADOOPERACION      CHAR(2)         NOT NULL,
    FECHAHORADIAPAGO        TIMESTAMP       NOT NULL,
    NOMBRECLIENTECONVENIO   VARCHAR(100)    NULL,
    FLAGRECAUDACION         CHAR(1)         NOT NULL DEFAULT 'N',
    FLAGDEBITOAUTOMATICO    CHAR(1)         NOT NULL DEFAULT 'N',
    FLAGRECARGA             CHAR(1)         NOT NULL DEFAULT 'N',
    MONTOPAGADO             NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOCOMISION           NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOMORA               NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOTOTAL              NUMERIC(14,4)   NOT NULL DEFAULT 0,
    TIPOCAMBIO              NUMERIC(8,4)    NOT NULL DEFAULT 1,
    FECULTACTUALIZACION     TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- Giros / transferencias interbancarias
CREATE TABLE DNOCLIENTEUSUARIO (
    PKNOCLIENTEUSUARIO      SERIAL          PRIMARY KEY,
    CODCLIENTEGIRO          VARCHAR(20)     NULL,
    NOMBRECOMPLETO          VARCHAR(100)    NOT NULL,
    TELEFONO                VARCHAR(15)     NULL,
    PKTIPODOCUMENTOIDENTIDAD INT            NULL REFERENCES DTIPODOCUMENTOIDENTIDAD(PKTIPODOCUMENTOIDENTIDAD),
    CODTIPODOCUMENTOIDENTIDAD CHAR(2)       NULL,
    DESTIPODOCUMENTOIDENTIDAD VARCHAR(40)   NULL,
    NUMDOCUMENTOIDENTIDAD   VARCHAR(12)     NULL,
    FECULTACTUALIZACION     TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DESTADOGIRO (
    PKESTADOGIRO        SERIAL          PRIMARY KEY,
    CODESTADOGIRO       CHAR(2)         NOT NULL UNIQUE,
    DESESTADOGIRO       VARCHAR(40)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE DGIRO (
    PKGIRO              SERIAL          PRIMARY KEY,
    CODGIRO             VARCHAR(20)     NOT NULL UNIQUE,
    PKNOCLIENTEUSUARIO  INT             NULL REFERENCES DNOCLIENTEUSUARIO(PKNOCLIENTEUSUARIO),
    PKCLIENTE           INT             NULL REFERENCES DCLIENTE(PKCLIENTE),
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE FGIRO (
    PKGIRO                  INT             NOT NULL REFERENCES DGIRO(PKGIRO),
    PERIODODIAREGISTRO      INT             NOT NULL REFERENCES DTIEMPO(PERIODODIA),
    FECHAHORAREGISTRO       TIMESTAMP       NOT NULL,
    PKAUXILIARENVIO         INT             NULL REFERENCES DAUXILIAR(PKAUXILIAR),
    PKAUXILIARDESTINO       INT             NULL REFERENCES DAUXILIAR(PKAUXILIAR),
    PKAGENCIAENVIO          INT             NOT NULL REFERENCES DAGENCIA(PKAGENCIA),
    PKAGENCIADESTINO        INT             NULL REFERENCES DAGENCIA(PKAGENCIA),
    PKESTADOGIRO            INT             NOT NULL REFERENCES DESTADOGIRO(PKESTADOGIRO),
    PKNOCLIENTEUSUARIOREM   INT             NULL REFERENCES DNOCLIENTEUSUARIO(PKNOCLIENTEUSUARIO),
    PKCLIENTEREM            INT             NULL REFERENCES DCLIENTE(PKCLIENTE),
    PKNOCLIENTEUSUARIOBEN   INT             NULL REFERENCES DNOCLIENTEUSUARIO(PKNOCLIENTEUSUARIO),
    PKCLIENTEBEN            INT             NULL REFERENCES DCLIENTE(PKCLIENTE),
    PKMONEDA                INT             NOT NULL REFERENCES DMONEDA(PKMONEDA),
    PKCANALGIRO             INT             NULL REFERENCES DCANALGIRO(PKCANALGIRO),
    PERIODODIAPAGO          INT             NULL REFERENCES DTIEMPO(PERIODODIA),
    MONTOTOTALCOBRO         NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOENVIADO            NUMERIC(14,4)   NOT NULL DEFAULT 0,
    MONTOCOMISIONCOBRO      NUMERIC(14,4)   NOT NULL DEFAULT 0,
    FLAGCAMBIODESTINO       CHAR(1)         NOT NULL DEFAULT 'N',
    TIPOCAMBIOGIRO          NUMERIC(8,4)    NOT NULL DEFAULT 1,
    TIPOGIRO                CHAR(2)         NULL,
    FECHAHORAPAGO           TIMESTAMP       NULL,
    FECULTACTUALIZACION     TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY (PKGIRO, PERIODODIAREGISTRO)
);

-- Afiliación débito automático
CREATE TABLE FDEBITOAFILIACION (
    PKFDEBITOAFILIACION     SERIAL          PRIMARY KEY,
    CODAFILIACIONDEBITO     VARCHAR(20)     NOT NULL UNIQUE,
    PKCUENTAAHORRO          INT             NOT NULL REFERENCES DCUENTAAHORRO(PKCUENTAAHORRO),
    PERIODODIAAFILIACION    INT             NOT NULL REFERENCES DTIEMPO(PERIODODIA),
    FECHAHORAAFILIACION     TIMESTAMP       NOT NULL,
    PERIODODIADESAFILACION  INT             NULL REFERENCES DTIEMPO(PERIODODIA),
    FECHAHORADESAFILACION   TIMESTAMP       NULL,
    PKCLIENTE               INT             NOT NULL REFERENCES DCLIENTE(PKCLIENTE),
    PKAUXILIAR              INT             NULL REFERENCES DAUXILIAR(PKAUXILIAR),
    PKMONEDA                INT             NOT NULL REFERENCES DMONEDA(PKMONEDA),
    FLAGCUENTAPRINCIPAL     CHAR(1)         NOT NULL DEFAULT 'N',
    FLAGAFILIADO            CHAR(1)         NOT NULL DEFAULT 'S',
    FECULTACTUALIZACION     TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- ============================================================
-- BLOQUE 11: RIESGOS Y ENTIDADES FINANCIERAS
-- ============================================================

CREATE TABLE DENTIDADFINANCIERA (
    PKENTIDADFINANCIERA SERIAL          PRIMARY KEY,
    CODENTIDADFINANCIERA CHAR(4)        NOT NULL UNIQUE,
    DESENTIDADFINANCIERA VARCHAR(80)    NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- Deuda multi-entidad SBS por cliente/mes
CREATE TABLE FENTIDADESRELACIONADAS (
    PERIODOMES          INT             NOT NULL REFERENCES DTIEMPOMES(PERIODOMES),
    PKENTIDADFINANCIERA INT             NOT NULL REFERENCES DENTIDADFINANCIERA(PKENTIDADFINANCIERA),
    PKCLIENTE           INT             NOT NULL REFERENCES DCLIENTE(PKCLIENTE),
    NROENTIDADESRELACIONADAS SMALLINT   NOT NULL DEFAULT 0,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY (PERIODOMES, PKENTIDADFINANCIERA, PKCLIENTE)
);

-- ============================================================
-- BLOQUE 12: METAS Y KPIs (Power BI + Core Financiero)
-- ============================================================

CREATE TABLE DTIPOCREDITO (
    PKTIPOCREDITO       SERIAL          PRIMARY KEY,
    CODTIPOCREDITO      CHAR(2)         NOT NULL UNIQUE,
    DESTIPOCREDITO      VARCHAR(50)     NOT NULL,
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE FMETASASESOR (
    PERIODOMES                  INT             NOT NULL REFERENCES DTIEMPOMES(PERIODOMES),
    PKASESOR                    INT             NOT NULL REFERENCES DASESOR(PKASESOR),
    SALDOCOLOCACIONES_META      NUMERIC(16,4)   NOT NULL DEFAULT 0,
    NROCLIENTES_META            INT             NOT NULL DEFAULT 0,
    CARTERAATRASADA_META        NUMERIC(16,4)   NOT NULL DEFAULT 0,
    CLIENTESNUEVOS_META         INT             NOT NULL DEFAULT 0,
    RATIOMORA_META              NUMERIC(8,4)    NOT NULL DEFAULT 0,
    SALDOCOLOCACIONES_REAL      NUMERIC(16,4)   NOT NULL DEFAULT 0,
    NROCLIENTES_REAL            INT             NOT NULL DEFAULT 0,
    CARTERAATRASADA_REAL        NUMERIC(16,4)   NOT NULL DEFAULT 0,
    CLIENTESNUEVOS_REAL         INT             NOT NULL DEFAULT 0,
    RATIOMORA_REAL              NUMERIC(8,4)    NOT NULL DEFAULT 0,
    FECULTACTUALIZACION         TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY (PERIODOMES, PKASESOR)
);

CREATE TABLE FMETAAGENCIA (
    PERIODOMES                  INT             NOT NULL REFERENCES DTIEMPOMES(PERIODOMES),
    PKAGENCIA                   INT             NOT NULL REFERENCES DAGENCIA(PKAGENCIA),
    SALDOCOLOCACIONES_META      NUMERIC(16,4)   NOT NULL DEFAULT 0,
    NROCLIENTES_META            INT             NOT NULL DEFAULT 0,
    CARTERAATRASADA_META        NUMERIC(16,4)   NOT NULL DEFAULT 0,
    CLIENTESNUEVOS_META         INT             NOT NULL DEFAULT 0,
    RATIOMORA_META              NUMERIC(8,4)    NOT NULL DEFAULT 0,
    SALDOCOLOCACIONES_REAL      NUMERIC(16,4)   NOT NULL DEFAULT 0,
    NROCLIENTES_REAL            INT             NOT NULL DEFAULT 0,
    CARTERAATRASADA_REAL        NUMERIC(16,4)   NOT NULL DEFAULT 0,
    CLIENTESNUEVOS_REAL         INT             NOT NULL DEFAULT 0,
    RATIOMORA_REAL              NUMERIC(8,4)    NOT NULL DEFAULT 0,
    FECULTACTUALIZACION         TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY (PERIODOMES, PKAGENCIA)
);

CREATE TABLE FMETATIPOCREDITO (
    PERIODOMES                  INT             NOT NULL REFERENCES DTIEMPOMES(PERIODOMES),
    PKTIPOCREDITO               INT             NOT NULL REFERENCES DTIPOCREDITO(PKTIPOCREDITO),
    SALDOCOLOCACIONES_META      NUMERIC(16,4)   NOT NULL DEFAULT 0,
    NROCLIENTES_META            INT             NOT NULL DEFAULT 0,
    CARTERAATRASADA_META        NUMERIC(16,4)   NOT NULL DEFAULT 0,
    RATIOMORA_META              NUMERIC(8,4)    NOT NULL DEFAULT 0,
    SALDOCOLOCACIONES_REAL      NUMERIC(16,4)   NOT NULL DEFAULT 0,
    NROCLIENTES_REAL            INT             NOT NULL DEFAULT 0,
    CARTERAATRASADA_REAL        NUMERIC(16,4)   NOT NULL DEFAULT 0,
    RATIOMORA_REAL              NUMERIC(8,4)    NOT NULL DEFAULT 0,
    FECULTACTUALIZACION         TIMESTAMP       NOT NULL DEFAULT NOW(),
    PRIMARY KEY (PERIODOMES, PKTIPOCREDITO)
);

-- ============================================================
-- BLOQUE 13: HOME BANKING - USUARIOS Y SESIONES
-- ============================================================

-- Tabla nueva (no existe en DW — lógica de aplicación)
CREATE TABLE USUARIOS_HOMEBANKING (
    PKUSUARIO           SERIAL          PRIMARY KEY,
    PKCLIENTE           INT             NOT NULL REFERENCES DCLIENTE(PKCLIENTE) UNIQUE,
    USERNAME            VARCHAR(50)     NOT NULL UNIQUE,
    PASSWORD_HASH       VARCHAR(255)    NOT NULL,  -- bcrypt
    TOKEN_REFRESH       VARCHAR(500)    NULL,
    ULTIMO_ACCESO       TIMESTAMP       NULL,
    INTENTOS_FALLIDOS   SMALLINT        NOT NULL DEFAULT 0,
    BLOQUEADO           CHAR(1)         NOT NULL DEFAULT 'N',
    ACTIVO              CHAR(1)         NOT NULL DEFAULT 'S',
    FECULTACTUALIZACION TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- ============================================================
-- BLOQUE 14: INDICES ESTRATEGICOS
-- (optimizados para home banking, core financiero y Power BI)
-- ============================================================

-- FAGCUENTACREDITO - los más consultados
CREATE INDEX IX_FAG_CLI       ON FAGCUENTACREDITO(PKCLIENTE);
CREATE INDEX IX_FAG_AGE       ON FAGCUENTACREDITO(PKAGENCIA);
CREATE INDEX IX_FAG_ASE       ON FAGCUENTACREDITO(PKASESOR);
CREATE INDEX IX_FAG_PER       ON FAGCUENTACREDITO(PERIODOMES);
CREATE INDEX IX_FAG_EST       ON FAGCUENTACREDITO(PKESTADOCREDITO);
CREATE INDEX IX_FAG_CAR       ON FAGCUENTACREDITO(FLAGJUDICIAL, FLAGCASTIGADO);
CREATE INDEX IX_FAG_DIA       ON FAGCUENTACREDITO(DIASATRASOCREDITO);

-- FPLANPAGOMES - home banking cuotas
CREATE INDEX IX_FPP_CTA       ON FPLANPAGOMES(PKCUENTACREDITO);
CREATE INDEX IX_FPP_CLI       ON FPLANPAGOMES(PKCLIENTE);
CREATE INDEX IX_FPP_EST       ON FPLANPAGOMES(CODESTADOCUOTA);
CREATE INDEX IX_FPP_VEN       ON FPLANPAGOMES(FECHAVENCIMIENTOPAGOCUOTA);

-- FOPERACIONES - movimientos home banking
CREATE INDEX IX_FOP_CTA       ON FOPERACIONES(PKCUENTACREDITO);
CREATE INDEX IX_FOP_AHO       ON FOPERACIONES(PKCUENTAAHORRO);
CREATE INDEX IX_FOP_FEC       ON FOPERACIONES(FECHAHORAOPERACION DESC);
CREATE INDEX IX_FOP_CAN       ON FOPERACIONES(PKCANALTRANSACCIONAL);

-- FCUENTAAHORRO - saldos home banking
CREATE INDEX IX_FCA_CLI       ON FCUENTAAHORRO(PKCLIENTE);
CREATE INDEX IX_FCA_PER       ON FCUENTAAHORRO(PERIODODIA);

-- DCLIENTE - búsquedas frecuentes
CREATE INDEX IX_CLI_DOC       ON DCLIENTE(NUMERODOCUMENTOIDENTIDAD);
CREATE INDEX IX_CLI_SBS       ON DCLIENTE(CODSBS);
CREATE INDEX IX_CLI_EMI       ON DCLIENTE(EMAIL);

-- DSOLICITUD
CREATE INDEX IX_SOL_CLI       ON DSOLICITUD(PKCLIENTE);
CREATE INDEX IX_SOL_AGE       ON DSOLICITUD(PKAGENCIA);
CREATE INDEX IX_SOL_ASE       ON DSOLICITUD(PKASESOR);

-- Metas - Power BI
CREATE INDEX IX_MAS_PER       ON FMETASASESOR(PERIODOMES, PKASESOR);
CREATE INDEX IX_MAG_PER       ON FMETAAGENCIA(PERIODOMES, PKAGENCIA);

-- USUARIOS_HOMEBANKING
CREATE UNIQUE INDEX IX_USR_USN ON USUARIOS_HOMEBANKING(USERNAME);
CREATE INDEX IX_USR_CLI        ON USUARIOS_HOMEBANKING(PKCLIENTE);
